"""Counts for docs/reversal_2012_2026_data_report_v2.md: what data version 2 changed against version 1.

Data only: counts of name-weeks, slots, rows, statuses and checks. No signal, strategy return, portfolio return or
cross-stock return aggregate is computed, and no vendor price level is written. Version 1 and version 2 files are
only read. Output (may go to git): ``output/research_only/reversal_2012_2026/v2_report/`` (``summary.json`` and a few
CSVs of counts and IDs).

    PYTHONPATH=. .venv/bin/python scripts/reversal_data_v2_report.py
"""
from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
MAIN = Path("/Users/bytedance/code/quant_stocks")
V = {"v1": (MAIN / "research_cache/reversal_2012_2026", ROOT / "output/research_only/reversal_2012_2026/inputs"),
     "v2": (MAIN / "research_cache/reversal_2012_2026_v2", ROOT / "output/research_only/reversal_2012_2026/inputs_v2")}
FILL = MAIN / "research_cache/reversal_2012_2026_v2_fill"
OUT = ROOT / "output/research_only/reversal_2012_2026/v2_report"


def checks(inputs: Path) -> dict:
    v = json.loads((inputs / "validation_summary.json").read_text())
    return {c["check"]: c for c in v["checks"]}, v


def table_a(cache: Path) -> dict:
    u = json.loads((cache / "universe/universe_summary.json").read_text())
    return u["check_6_three_estimates"]["by_year"]


def weekly(cache: Path) -> pd.DataFrame:
    return pd.read_csv(cache / "universe/weekly_listed.csv.gz",
                       usecols=["week_end", "security_id", "missing", "missing_reason", "evidence", "p_top250",
                                "dv50_rank", "dv20_rank"], dtype={"security_id": str})


def _pct(x) -> str:
    return "" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{100 * float(x):.3f}%"


def render_tables(out: dict, share: pd.DataFrame, by: pd.DataFrame) -> str:
    """The report's tables as markdown (regenerated by each run, so a rebuild after the long fetch refreshes them)."""
    lines = ["#### Missing share of top-250 slots by year, v1 against v2 (Table B: validate check 6, unfillable names; "
             "Table A: step 12, every non-pending reason)", "",
             "| Year | B model v1 | B model v2 | B calibrated v2 | B upper v2 | A model v1 | A model v2 | A upper v1 | A upper v2 | "
             "v2 over 2% (B model) |", "|---|---|---|---|---|---|---|---|---|---|"]
    for r in share.itertuples():
        lines.append(f"| {r.year} | {_pct(r.v1_B_model)} | {_pct(r.v2_B_model)} | {_pct(r.v2_B_calibrated)} | "
                     f"{_pct(r.v2_B_upper)} | {_pct(r.v1_A_model)} | {_pct(r.v2_A_model)} | {_pct(r.v1_A_upper)} | "
                     f"{_pct(r.v2_A_upper)} | {'**yes**' if r.v2_B_over_2pct else 'no'} |")
    lines += ["", "#### Gap slots closed by year (v1 missing listed name-weeks that v2 prices and ranks)", "",
              "| Year | v1 missing name-weeks | closed in v2 | v1 expected top-250 slots (model) | of which closed | closed and in "
              "v2's top 250 |", "|---|---|---|---|---|---|"]
    for r in by.itertuples():
        lines.append(f"| {r.year} | {r.v1_missing_name_weeks:,} | {int(r.closed_name_weeks):,} | {r.v1_expected_top250_slots:,.2f} | "
                     f"{r.expected_slots_closed:,.2f} | {int(r.closed_and_ranked_top250):,} |")
    tot = by[["v1_missing_name_weeks", "closed_name_weeks", "v1_expected_top250_slots", "expected_slots_closed",
              "closed_and_ranked_top250"]].sum()
    lines.append(f"| all | {int(tot.iloc[0]):,} | {int(tot.iloc[1]):,} | {tot.iloc[2]:,.2f} | {tot.iloc[3]:,.2f} | "
                 f"{int(tot.iloc[4]):,} |")
    v = out["validate"]
    lines += ["", f"#### Validate: v1 {v['v1']} against v2 {v['v2']}", "", "| Check | v1 | v2 |", "|---|---|---|"]
    for r in v["changed"]:
        lines.append(f"| {r['check']} | {r['v1']} | {r['v2']} |")
    if not v["changed"]:
        lines.append("| (no check changed status) | | |")
    return "\n".join(lines)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    out: dict = {"built_utc": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
                 "no_returns_aggregated": True,
                 "note": "counts of name-weeks, slots, rows, statuses and checks only; no vendor price level"}
    # ---- the 2% rule: Table B (validate check 6, unfillable only) and Table A (step 12, every non-pending reason)
    tb, ta = {}, {}
    for ver, (cache, inputs) in V.items():
        c, _ = checks(inputs)
        tb[ver] = c["universe_unfillable"]["numbers"]["by_year"]
        ta[ver] = table_a(cache)
    rows = []
    for y in sorted(tb["v1"], key=int):
        r = {"year": int(y)}
        for ver in V:
            b, a = tb[ver].get(y, {}), ta[ver].get(y, {})
            r.update({f"{ver}_B_model": b.get("share"), f"{ver}_B_calibrated": b.get("share_calibrated"),
                      f"{ver}_B_upper": b.get("share_upper"), f"{ver}_B_name_weeks": b.get("name_weeks"),
                      f"{ver}_A_model": a.get("model"), f"{ver}_A_calibrated": a.get("calibrated"),
                      f"{ver}_A_upper": a.get("upper")})
        r["v2_B_over_2pct"] = bool((r["v2_B_model"] or 0) > 0.02)
        r["v1_B_over_2pct"] = bool((r["v1_B_model"] or 0) > 0.02)
        rows.append(r)
    share = pd.DataFrame(rows)
    share.to_csv(OUT / "missing_share_by_year.csv", index=False)
    out["missing_share_by_year"] = share.to_dict("records")
    # ---- gap slots closed: v1 missing name-weeks that v2 ranks, weighted by v1's expected top-250 count
    w1, w2 = weekly(V["v1"][0]), weekly(V["v2"][0])
    m1 = w1[w1["missing"] == True].copy()  # noqa: E712
    key = ["week_end", "security_id"]
    j = m1.merge(w2[key + ["missing", "dv50_rank", "dv20_rank"]].rename(
        columns={"missing": "missing_v2", "dv50_rank": "dv50_v2", "dv20_rank": "dv20_v2"}), on=key, how="left")
    j["closed"] = j["missing_v2"].eq(False)
    j["closed_top250"] = j["closed"] & ((j["dv50_v2"] <= 250) | (j["dv20_v2"] <= 250))
    j["year"] = j["week_end"].str[:4].astype(int)
    j["p"] = j["p_top250"].astype(float).fillna(0.0)
    by = j.groupby("year").agg(v1_missing_name_weeks=("closed", "size"), closed_name_weeks=("closed", "sum"),
                               v1_expected_top250_slots=("p", "sum"),
                               expected_slots_closed=("p", lambda s: float(s[j.loc[s.index, "closed"]].sum())),
                               closed_and_ranked_top250=("closed_top250", "sum"))
    by = by.reset_index()
    by["expected_slots_closed"] = by["expected_slots_closed"].round(2)
    by["v1_expected_top250_slots"] = by["v1_expected_top250_slots"].round(2)
    by.to_csv(OUT / "gap_slots_closed_by_year.csv", index=False)
    out["gap_slots_closed_by_year"] = by.to_dict("records")
    out["gap_slots_closed_by_reason"] = j.groupby("missing_reason").agg(
        v1_name_weeks=("closed", "size"), closed=("closed", "sum"), v1_expected=("p", "sum")).round(2).reset_index().to_dict("records")
    new_missing = w2[(w2["missing"] == True)].merge(w1[key + ["missing"]].rename(columns={"missing": "m1"}), on=key,  # noqa: E712
                                                     how="left")
    out["name_weeks_missing_in_v2_not_in_v1"] = int((new_missing["m1"] != True).sum())  # noqa: E712
    # ---- panel rows by source and the fill
    p2 = pd.read_csv(V["v2"][0] / "prices/daily_panel.csv.gz", usecols=["security_id", "date", "src_primary", "flags"],
                     dtype=str)
    arch = p2[p2["src_primary"] == "archive"]
    out["panel_v2_rows_by_source"] = p2["src_primary"].value_counts().to_dict()
    out["archive_rows"] = {"rows": int(len(arch)), "securities": int(arch["security_id"].nunique()),
                           "by_year": arch["date"].str[:4].value_counts().sort_index().to_dict(),
                           "with_second_source_flag_free": None}
    flags = p2["flags"].fillna("")
    out["v2_flags"] = {f: int(flags.str.contains(f, regex=False).sum()) for f in
                       ("v2_fix:", "v2_third_vote:", "v2_splice_blank", "v2_majority:quantquote", "archive_csv",
                        "archive_page", "disagree_unresolved")}
    p1f = pd.read_csv(V["v1"][0] / "prices/daily_panel.csv.gz", usecols=["flags"], dtype=str)["flags"].fillna("")
    out["v1_disagree_unresolved_days"] = int(p1f.str.contains("disagree_unresolved", regex=False).sum())
    # ---- D5 names
    t1 = pd.read_csv(V["v1"][1] / "terminal_returns_2012_2026.csv", dtype=str, keep_default_na=False)
    t2 = pd.read_csv(V["v2"][1] / "terminal_returns_2012_2026.csv", dtype=str, keep_default_na=False)
    d5 = t1[t1["status"] == "awaiting_d5"][["security_id", "ticker", "delist_date"]]
    d5 = d5.merge(t2[["security_id", "status", "last_price_date", "price_source", "consideration_value_basis"]].rename(
        columns={"status": "status_v2", "last_price_date": "last_price_date_v2"}), on="security_id", how="left")
    ev_path = V["v2"][1] / "v2_d5_sec_evidence.csv"
    if ev_path.exists():
        ev = pd.read_csv(ev_path, dtype=str, keep_default_na=False)
        d5 = d5.merge(ev[["security_id", "decision", "accession", "otc_ticker"]], on="security_id", how="left")
    d5.to_csv(OUT / "d5_resolution.csv", index=False)
    out["d5"] = {"names": int(len(d5)), "status_v2": d5["status_v2"].value_counts().to_dict(),
                 "sec_decision": d5["decision"].value_counts().to_dict() if "decision" in d5 else {}}
    out["terminal_status_v1"] = t1["status"].value_counts().to_dict()
    out["terminal_status_v2"] = t2["status"].value_counts().to_dict()
    # ---- fixes
    fa = V["v2"][0] / "reconcile/v2_fixes_applied.csv"
    if fa.exists():
        f = pd.read_csv(fa, dtype=str, keep_default_na=False)
        keep = ["fix_id", "security_id", "ticker", "ex_date", "applied", "reason", "children_sources",
                "children_second_source"]
        f[keep].to_csv(OUT / "fixes_applied.csv", index=False)
        out["fixes"] = f[keep].to_dict("records")
    # ---- validate
    c1, v1 = checks(V["v1"][1])
    c2, v2 = checks(V["v2"][1])
    vt = pd.DataFrame([{"check": k, "v1": c1[k]["status"], "v2": c2.get(k, {}).get("status", "absent")} for k in c1])
    vt.to_csv(OUT / "validate_v1_v2.csv", index=False)
    out["validate"] = {"v1": {s: int((vt["v1"] == s).sum()) for s in ("pass", "fail", "no_input")},
                       "v2": {s: int((vt["v2"] == s).sum()) for s in ("pass", "fail", "no_input")},
                       "changed": vt[vt["v1"] != vt["v2"]].to_dict("records"),
                       "v2_generated_utc": v2.get("generated_utc")}
    # ---- fetch status of the long archive run
    prog = FILL / "progress.json"
    out["archive_fetch"] = json.loads(prog.read_text()) if prog.exists() else {}
    if (FILL / "targets.csv").exists():
        t = pd.read_csv(FILL / "targets.csv", dtype=str)
        out["archive_fetch"]["target_securities"] = int(t["security_id"].nunique())
    (OUT / "summary.json").write_text(json.dumps(out, indent=1, default=str) + "\n")
    (OUT / "tables.md").write_text(render_tables(out, share, by) + "\n")
    print(json.dumps({k: out[k] for k in ("validate", "d5", "v2_flags", "archive_rows")}, indent=1, default=str))
    return 0


if __name__ == "__main__":
    sys.exit(main())
